import { Trophy, Lock, Info } from 'lucide-react';
import SlideTypeHeader from '../common/SlideTypeHeader';
import { useTranslation } from 'react-i18next';

const LeaderboardEditor = ({ slide }) => {
  const { t } = useTranslation();
  const isAutoGenerated = slide?.leaderboardSettings?.isAutoGenerated;
  const displayCount = slide?.leaderboardSettings?.displayCount || 10;

  return (
    <div className="h-full overflow-y-auto scrollbar-thin bg-[#1F1F1F] text-[#E0E0E0]">
      <SlideTypeHeader type="leaderboard" />

      {/* Read-only Notice */}
      <div className="p-4 border-b border-[#2A2A2A] bg-[#2A2A2A]">
        <div className="flex items-start gap-3">
          <Lock className="h-5 w-5 text-[#FFA726] flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="text-sm font-medium text-[#E0E0E0] mb-1">
              {t('slide_editors.leaderboard.read_only_title')}
            </h3>
            <p className="text-xs text-[#9E9E9E]">
              {t('slide_editors.leaderboard.read_only_description')}
            </p>
          </div>
        </div>
      </div>

      {/* Slide Title */}
      <div className="p-4 border-b border-[#2A2A2A]">
        <label className="block text-sm font-medium text-[#E0E0E0] mb-2">
          {t('slide_editors.leaderboard.slide_title_label')}
        </label>
        <div className="px-3 py-2 border border-[#2A2A2A] rounded-lg text-sm bg-[#232323] text-[#9E9E9E]">
          {slide?.question || t('slide_editors.leaderboard.default_title')}
        </div>
      </div>

      {/* Display Settings */}
      <div className="p-4 border-b border-[#2A2A2A]">
        <label className="block text-sm font-medium text-[#E0E0E0] mb-2">
          {t('slide_editors.leaderboard.display_settings_label')}
        </label>
        <div className="space-y-2">
          <div className="flex items-center justify-between p-2 bg-[#232323] rounded-lg">
            <span className="text-sm text-[#E0E0E0]">{t('slide_editors.leaderboard.top_participants')}</span>
            <span className="text-sm text-[#4CAF50] font-medium">{displayCount}</span>
          </div>
          {isAutoGenerated && (
            <div className="flex items-center justify-between p-2 bg-[#232323] rounded-lg">
              <span className="text-sm text-[#E0E0E0]">{t('slide_editors.leaderboard.auto_generated')}</span>
              <span className="text-xs px-2 py-1 bg-[#4CAF50] text-[#1F1F1F] rounded-full font-medium">
                {t('slide_editors.leaderboard.yes')}
              </span>
            </div>
          )}
        </div>
      </div>

      {/* Leaderboard Preview */}
      <div className="p-4 border-b border-[#2A2A2A]">
        <label className="text-sm font-medium text-[#E0E0E0] mb-3 flex items-center gap-2">
          <Trophy className="h-4 w-4 text-[#FFD700]" />
          {t('slide_editors.leaderboard.leaderboard_preview')}
        </label>
        <div className="space-y-2">
          {[1, 2, 3].map((rank) => (
            <div
              key={rank}
              className="flex items-center gap-3 p-3 bg-[#232323] rounded-lg border border-[#2A2A2A]"
            >
              <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${
                rank === 1 ? 'bg-[#FFD700] text-[#1F1F1F]' :
                rank === 2 ? 'bg-[#C0C0C0] text-[#1F1F1F]' :
                'bg-[#CD7F32] text-[#1F1F1F]'
              }`}>
                {rank}
              </div>
              <div className="flex-1">
                <div className="text-sm text-[#E0E0E0] font-medium">
                  {t('slide_editors.leaderboard.participant', { rank })}
                </div>
                <div className="text-xs text-[#9E9E9E]">
                  {t('slide_editors.leaderboard.example_participant_name')}
                </div>
              </div>
              <div className="text-right">
                <div className="text-sm text-[#4CAF50] font-bold">
                  {1000 - (rank - 1) * 100}
                </div>
                <div className="text-xs text-[#9E9E9E]">
                  {t('slide_editors.leaderboard.points')}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Information */}
      <div className="p-4 bg-[#232323]">
        <div className="flex items-start gap-3">
          <Info className="h-5 w-5 text-[#2196F3] flex-shrink-0 mt-0.5" />
          <div className="space-y-2 text-xs text-[#9E9E9E]">
            <p>
              <strong className="text-[#E0E0E0]">{t('slide_editors.leaderboard.how_it_works')}</strong>
            </p>
            <ul className="space-y-1 ml-4 list-disc">
              <li>{t('slide_editors.leaderboard.info_item_1')}</li>
              <li>{t('slide_editors.leaderboard.info_item_2')}</li>
              <li>{t('slide_editors.leaderboard.info_item_3')}</li>
              <li>{t('slide_editors.leaderboard.info_item_4')}</li>
              <li>{t('slide_editors.leaderboard.info_item_5')}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LeaderboardEditor;