const Slide = require('../models/Slide');
const quizScoringService = require('./quizScoringService');

/**
 * Leaderboard Service
 * Handles automatic creation and management of leaderboard slides
 */

/**
 * Create a leaderboard slide after a quiz slide
 * @param {Object} params
 * @param {string} params.presentationId
 * @param {string} params.quizSlideId
 * @param {number} params.quizSlideOrder
 * @returns {Promise<Object>} - Created leaderboard slide
 */
async function createLeaderboardSlide({ presentationId, quizSlideId, quizSlideOrder }) {
  try {
    // Check if leaderboard already exists for this quiz
    const existingLeaderboard = await Slide.findOne({
      presentationId,
      type: 'leaderboard',
      'leaderboardSettings.linkedQuizSlideId': quizSlideId
    });

    if (existingLeaderboard) {
      console.log(`Leaderboard already exists for quiz ${quizSlideId}`);
      return existingLeaderboard;
    }

    // Get the quiz slide to extract question
    const quizSlide = await Slide.findById(quizSlideId);
    if (!quizSlide) {
      throw new Error('Quiz slide not found');
    }

    // Increment order of all slides after the quiz
    await Slide.updateMany(
      {
        presentationId,
        order: { $gt: quizSlideOrder }
      },
      {
        $inc: { order: 1 }
      }
    );

    // Create leaderboard slide
    const leaderboardSlide = new Slide({
      presentationId,
      type: 'leaderboard',
      question: 'Quiz Leaderboard',
      order: quizSlideOrder + 1,
      leaderboardSettings: {
        linkedQuizSlideId: quizSlideId,
        isAutoGenerated: true,
        displayCount: 10
      }
    });

    await leaderboardSlide.save();
    console.log(`Created leaderboard slide for quiz ${quizSlideId}`);
    
    return leaderboardSlide;
  } catch (error) {
    console.error('Error creating leaderboard slide:', error);
    throw error;
  }
}

/**
 * Check if a quiz slide needs a leaderboard and create it
 * @param {string} presentationId
 * @param {string} quizSlideId
 * @returns {Promise<Object|null>} - Created leaderboard or null
 */
async function ensureLeaderboardForQuiz(presentationId, quizSlideId) {
  try {
    const quizSlide = await Slide.findById(quizSlideId);
    
    if (!quizSlide || quizSlide.type !== 'quiz') {
      return null;
    }

    // Check if there are any responses for this quiz
    const Response = require('../models/Response');
    const responseCount = await Response.countDocuments({ slideId: quizSlideId });

    if (responseCount === 0) {
      console.log(`No responses for quiz ${quizSlideId}, skipping leaderboard creation`);
      return null;
    }

    return await createLeaderboardSlide({
      presentationId,
      quizSlideId,
      quizSlideOrder: quizSlide.order
    });
  } catch (error) {
    console.error('Error ensuring leaderboard for quiz:', error);
    throw error;
  }
}

/**
 * Get leaderboard data for a specific quiz
 * @param {string} presentationId
 * @param {string} quizSlideId
 * @param {number} limit
 * @returns {Promise<Array>} - Leaderboard data
 */
async function getLeaderboardForQuiz(presentationId, quizSlideId, limit = 10) {
  try {
    return await quizScoringService.getLeaderboardWithDeltas(
      presentationId,
      quizSlideId,
      limit
    );
  } catch (error) {
    console.error('Error getting leaderboard for quiz:', error);
    throw error;
  }
}

/**
 * Delete leaderboard slide when quiz is deleted
 * @param {string} quizSlideId
 * @returns {Promise<Object>} - Delete result
 */
async function deleteLeaderboardForQuiz(quizSlideId) {
  try {
    const result = await Slide.deleteOne({
      type: 'leaderboard',
      'leaderboardSettings.linkedQuizSlideId': quizSlideId,
      'leaderboardSettings.isAutoGenerated': true
    });
    
    console.log(`Deleted leaderboard for quiz ${quizSlideId}`);
    return result;
  } catch (error) {
    console.error('Error deleting leaderboard for quiz:', error);
    throw error;
  }
}

/**
 * Create leaderboards for all quizzes in a presentation that have responses
 * @param {string} presentationId
 * @returns {Promise<Array>} - Array of created leaderboard slides
 */
async function createLeaderboardsForPresentation(presentationId) {
  try {
    const quizSlides = await Slide.find({
      presentationId,
      type: 'quiz'
    }).sort({ order: 1 });

    const createdLeaderboards = [];

    for (const quizSlide of quizSlides) {
      const leaderboard = await ensureLeaderboardForQuiz(
        presentationId,
        quizSlide._id.toString()
      );
      
      if (leaderboard) {
        createdLeaderboards.push(leaderboard);
      }
    }

    return createdLeaderboards;
  } catch (error) {
    console.error('Error creating leaderboards for presentation:', error);
    throw error;
  }
}

module.exports = {
  createLeaderboardSlide,
  ensureLeaderboardForQuiz,
  getLeaderboardForQuiz,
  deleteLeaderboardForQuiz,
  createLeaderboardsForPresentation
};
